### PR TITLE
Fix for missing previous xhardstate

### PR DESCRIPTION
**Pull request by zerwes**
## General information

Avoid failing notifications observed in the raw edition after upgrade to 2.4.x

## Bug reports

In some cases notifications will fail in the raw edition due to some missing VARs with the error
`jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'PREVIOUSSERVICEHARDSTATE'`

More details can be found in https://forum.checkmk.com/t/after-upgrade-from-2-3-x-to-2-4-x-raw-sporadically-failing-notifications-with-jinja2-exceptions-undefinederror-dict-object-has-no-attribute-previousservicehardstate/55347

OS used : Debian GNU/Linux 12 (bookworm)

## Proposed changes

The proposed changes just assure undefined values for the `PREVIOUS[SERVICE|HOST]HARDSTATE` in the jinja2 mail notification templates are set to some somehow sane defaults in order to avoid failing notifications.

### CODE REVIEW

**Comment by Yogibaer75** [comment]
I found also a enterprise installation today what is affected from this problem. So it is not only a RAW edition problem.
